// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package db

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceApp struct {
	Svc                  string   `protobuf:"bytes,1,opt,name=svc,proto3" json:"svc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceApp) Reset()         { *m = ServiceApp{} }
func (m *ServiceApp) String() string { return proto.CompactTextString(m) }
func (*ServiceApp) ProtoMessage()    {}
func (*ServiceApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *ServiceApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceApp.Unmarshal(m, b)
}
func (m *ServiceApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceApp.Marshal(b, m, deterministic)
}
func (m *ServiceApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceApp.Merge(m, src)
}
func (m *ServiceApp) XXX_Size() int {
	return xxx_messageInfo_ServiceApp.Size(m)
}
func (m *ServiceApp) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceApp.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceApp proto.InternalMessageInfo

func (m *ServiceApp) GetSvc() string {
	if m != nil {
		return m.Svc
	}
	return ""
}

type ServiceDb struct {
	Host                 string      `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string      `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	User                 string      `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password             string      `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Dbname               string      `protobuf:"bytes,5,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Svc                  *ServiceApp `protobuf:"bytes,6,opt,name=svc,proto3" json:"svc,omitempty"`
	ConnectionDb         string      `protobuf:"bytes,7,opt,name=connectionDb,proto3" json:"connectionDb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServiceDb) Reset()         { *m = ServiceDb{} }
func (m *ServiceDb) String() string { return proto.CompactTextString(m) }
func (*ServiceDb) ProtoMessage()    {}
func (*ServiceDb) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *ServiceDb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDb.Unmarshal(m, b)
}
func (m *ServiceDb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDb.Marshal(b, m, deterministic)
}
func (m *ServiceDb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDb.Merge(m, src)
}
func (m *ServiceDb) XXX_Size() int {
	return xxx_messageInfo_ServiceDb.Size(m)
}
func (m *ServiceDb) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDb.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDb proto.InternalMessageInfo

func (m *ServiceDb) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ServiceDb) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *ServiceDb) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ServiceDb) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ServiceDb) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

func (m *ServiceDb) GetSvc() *ServiceApp {
	if m != nil {
		return m.Svc
	}
	return nil
}

func (m *ServiceDb) GetConnectionDb() string {
	if m != nil {
		return m.ConnectionDb
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceApp)(nil), "db.ServiceApp")
	proto.RegisterType((*ServiceDb)(nil), "db.ServiceDb")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4e, 0x03, 0x21,
	0x10, 0xc6, 0xa5, 0xad, 0xdb, 0x76, 0xfc, 0x13, 0x9d, 0x83, 0x21, 0x3d, 0x98, 0x0d, 0xa7, 0xc6,
	0xc3, 0x1e, 0xea, 0x03, 0x18, 0x23, 0x4f, 0x60, 0x9f, 0xa0, 0x03, 0x24, 0xee, 0x41, 0x20, 0xc0,
	0xae, 0xcf, 0xe7, 0x9b, 0x19, 0x58, 0xb2, 0x6a, 0x6f, 0xdf, 0xef, 0xc7, 0x30, 0xf9, 0x32, 0xb0,
	0xd1, 0xd4, 0xf9, 0xe0, 0x92, 0xc3, 0x85, 0x26, 0xf1, 0x08, 0x70, 0x34, 0x61, 0xec, 0x95, 0x79,
	0xf5, 0x1e, 0xef, 0x60, 0x19, 0x47, 0xc5, 0x59, 0xcb, 0xf6, 0xdb, 0xf7, 0x1c, 0xc5, 0x37, 0x83,
	0x6d, 0x1d, 0x90, 0x84, 0x08, 0xab, 0x0f, 0x17, 0x53, 0x1d, 0x28, 0x39, 0x3b, 0xef, 0x42, 0xe2,
	0x8b, 0xc9, 0xe5, 0x9c, 0xdd, 0x10, 0x4d, 0xe0, 0xcb, 0xc9, 0xe5, 0x8c, 0x3b, 0xd8, 0xf8, 0x53,
	0x8c, 0x5f, 0x2e, 0x68, 0xbe, 0x2a, 0x7e, 0x66, 0x7c, 0x80, 0x46, 0x93, 0x3d, 0x7d, 0x1a, 0x7e,
	0x59, 0x5e, 0x2a, 0x61, 0x3b, 0xf5, 0x69, 0x5a, 0xb6, 0xbf, 0x3a, 0xdc, 0x76, 0x9a, 0xba, 0xdf,
	0xb2, 0xa5, 0x1f, 0x0a, 0xb8, 0x56, 0xce, 0x5a, 0xa3, 0x52, 0xef, 0xac, 0x24, 0xbe, 0x2e, 0xff,
	0xff, 0xb9, 0xc3, 0x0b, 0xdc, 0xbf, 0xcd, 0x5c, 0x17, 0xe0, 0x13, 0xac, 0x8f, 0x26, 0x0d, 0x5e,
	0x12, 0x9e, 0x2d, 0xde, 0xdd, 0xfc, 0x61, 0x49, 0xe2, 0x82, 0x9a, 0x72, 0xaf, 0xe7, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0xeb, 0x38, 0xce, 0x3b, 0x01, 0x00, 0x00,
}
