// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: db.proto

package db

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ConnectionService service

type ConnectionService interface {
	SetupDb(ctx context.Context, in *ServiceApp, opts ...client.CallOption) (*ServiceDb, error)
}

type connectionService struct {
	c    client.Client
	name string
}

func NewConnectionService(name string, c client.Client) ConnectionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "db"
	}
	return &connectionService{
		c:    c,
		name: name,
	}
}

func (c *connectionService) SetupDb(ctx context.Context, in *ServiceApp, opts ...client.CallOption) (*ServiceDb, error) {
	req := c.c.NewRequest(c.name, "ConnectionService.SetupDb", in)
	out := new(ServiceDb)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConnectionService service

type ConnectionServiceHandler interface {
	SetupDb(context.Context, *ServiceApp, *ServiceDb) error
}

func RegisterConnectionServiceHandler(s server.Server, hdlr ConnectionServiceHandler, opts ...server.HandlerOption) error {
	type connectionService interface {
		SetupDb(ctx context.Context, in *ServiceApp, out *ServiceDb) error
	}
	type ConnectionService struct {
		connectionService
	}
	h := &connectionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ConnectionService{h}, opts...))
}

type connectionServiceHandler struct {
	ConnectionServiceHandler
}

func (h *connectionServiceHandler) SetupDb(ctx context.Context, in *ServiceApp, out *ServiceDb) error {
	return h.ConnectionServiceHandler.SetupDb(ctx, in, out)
}
